import type { ThemeConfig } from "antd";

export const heraTheme: ThemeConfig = {
  token: {
    colorPrimary: "#2ba63d",
    colorSuccess: "#199a3e",
    colorError: "#cf3a3f",
    colorWarning: "#b7791f",
    colorInfo: "#2f6fd0",
    colorBgContainer: "#ffffff",
    colorBgLayout: "#f2f2f2",
    colorBgElevated: "#ffffff",
    colorBorder: "#c6c6c6",
    colorBorderSecondary: "#dcdcdc",
    colorText: "#232323",
    colorTextSecondary: "#6d6d6d",
    colorTextTertiary: "#9a9a9a",
    colorTextPlaceholder: "#a8a8a8",
    borderRadius: 4,
    borderRadiusSM: 3,
    borderRadiusLG: 6,
    fontFamily: "'Inter Tight', 'Inter', system-ui, -apple-system, 'Segoe UI', sans-serif",
    fontSize: 13,
    fontSizeSM: 12,
    fontSizeLG: 14,
    lineHeight: 1.6,
    controlHeight: 28,
    controlHeightSM: 24,
    controlHeightLG: 32,
    boxShadow: "0 2px 8px rgba(0,0,0,.12)",
    boxShadowSecondary: "0 1px 4px rgba(0,0,0,.08)",
    paddingXS: 4,
    paddingSM: 8,
    padding: 12,
    paddingMD: 16,
    paddingLG: 24,
    marginXS: 4,
    marginSM: 8,
    margin: 12,
    marginMD: 16,
    marginLG: 24,
  },
  components: {
    Table: {
      headerBg: "#f0f0f0",
      headerColor: "#6d6d6d",
      rowHoverBg: "rgba(65,205,82,.06)",
      borderColor: "#eeeeee",
      fontSize: 12,
      cellPaddingInline: 12,
      cellPaddingBlock: 7,
      headerSortActiveBg: "#eaeaea",
    },
    Button: {
      controlHeight: 28,
      controlHeightSM: 24,
      controlHeightLG: 32,
      fontSize: 12,
      fontSizeLG: 13,
      borderRadius: 4,
    },
    Input: {
      controlHeight: 28,
      controlHeightSM: 24,
      activeBorderColor: "#2ba63d",
      hoverBorderColor: "#2ba63d",
      fontSize: 12,
    },
    Select: {
      controlHeight: 28,
      controlHeightSM: 24,
      fontSize: 12,
      optionFontSize: 12,
    },
    Form: {
      labelFontSize: 11,
      labelColor: "#7a7a7a",
      itemMarginBottom: 14,
      verticalLabelPadding: "0 0 4px",
    },
    Modal: {
      headerBg: "#f5f5f5",
      titleFontSize: 13,
      titleColor: "#232323",
    },
    Card: {
      paddingLG: 14,
      bodyPadding: 14,
    },
    Collapse: {
      headerBg: "#f5f5f5",
      contentBg: "#ffffff",
      borderRadiusLG: 6,
    },
    Tag: {
      fontSize: 11,
      borderRadiusSM: 3,
    },
    Tooltip: {
      fontSize: 12,
    },
    Badge: {
      fontSize: 11,
    },
    Switch: {
      colorPrimary: "#2ba63d",
    },
    Divider: {
      colorSplit: "#e4e4e4",
    },
  },
};
